variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

.test_template: &test_template
  stage: test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .cache/pip
  artifacts:
    expire_in: 1 day
    paths:
      - coverage.xml
  before_script:
    - pip install virtualenv
    - virtualenv env
  script:
    - make install
    - make test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

.sonar_template: &sonar_template
  stage: sonar
  image: ciricihq/gitlab-sonar-scanner
  before_script:
    - export SONAR_ANALYSIS_MODE=publish
    - projectVersion=$(awk -F\" '/^__version__ = / {print $2}' supercell/__init__.py)
    - echo sonar.projectVersion=${projectVersion} >> sonar-project.properties
    - echo "sonar.projectKey=RTR:${projectKey}" >> sonar-project.properties
    - 'echo "sonar.projectName=Python :: ${projectKey}" >> sonar-project.properties'
    - echo "sonar.sources=supercell" >> sonar-project.properties
  script:
    - tail -2 sonar-project.properties
    - ls -l coverage.xml
    - sonar-scanner-run.sh
  only:
    - develop

stages:
  - test
  - sonar

test:27:
  image: python:2.7
  <<: *test_template

test:36:
  image: python:3.6
  <<: *test_template

sonar:27:
  <<: *sonar_template
  dependencies:
    - test:27
  variables:
    projectKey: supercell-27

sonar:36:
  <<: *sonar_template
  dependencies:
    - test:36
  variables:
    projectKey: supercell-36
